from enum import Enum


class RiskLevel(Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RiskCategory(Enum):
    FINANCIAL = "FINANCIAL"
    MARKET = "MARKET"
    OPERATIONAL = "OPERATIONAL"
    CUSTOMER = "CUSTOMER"
    EXECUTION = "EXECUTION"
    COMPETITION = "COMPETITION"
    SEASONAL = "SEASONAL"
    SUPPLY_CHAIN = "SUPPLY_CHAIN"
    REGULATORY = "REGULATORY"
    BUSINESS_CONTINUITY = "BUSINESS_CONTINUITY"
